// Common IATA airline codes (2-letter). Curated worldwide list.
// Format: { code, name }
export type Airline = { code: string; name: string };

export const AIRLINES: Airline[] = [
  { code: "SV", name: "Saudia (Saudi Arabian Airlines)" },
  { code: "XY", name: "flynas" },
  { code: "F3", name: "flyadeal" },
  { code: "EK", name: "Emirates" },
  { code: "EY", name: "Etihad Airways" },
  { code: "QR", name: "Qatar Airways" },
  { code: "GF", name: "Gulf Air" },
  { code: "WY", name: "Oman Air" },
  { code: "KU", name: "Kuwait Airways" },
  { code: "RJ", name: "Royal Jordanian" },
  { code: "ME", name: "Middle East Airlines" },
  { code: "MS", name: "EgyptAir" },
  { code: "TK", name: "Turkish Airlines" },
  { code: "PK", name: "Pakistan International Airlines" },
  { code: "AI", name: "Air India" },
  { code: "IX", name: "Air India Express" },
  { code: "6E", name: "IndiGo" },
  { code: "UK", name: "Vistara" },
  { code: "SG", name: "SpiceJet" },
  { code: "QP", name: "Akasa Air" },
  { code: "G8", name: "GoAir / Go First" },
  { code: "BG", name: "Biman Bangladesh Airlines" },
  { code: "UL", name: "SriLankan Airlines" },
  { code: "PR", name: "Philippine Airlines" },
  { code: "5J", name: "Cebu Pacific" },
  { code: "MH", name: "Malaysia Airlines" },
  { code: "AK", name: "AirAsia" },
  { code: "D7", name: "AirAsia X" },
  { code: "OD", name: "Batik Air Malaysia" },
  { code: "SQ", name: "Singapore Airlines" },
  { code: "TR", name: "Scoot" },
  { code: "TG", name: "Thai Airways" },
  { code: "FD", name: "Thai AirAsia" },
  { code: "VN", name: "Vietnam Airlines" },
  { code: "VJ", name: "VietJet Air" },
  { code: "CX", name: "Cathay Pacific" },
  { code: "CI", name: "China Airlines" },
  { code: "BR", name: "EVA Air" },
  { code: "CA", name: "Air China" },
  { code: "MU", name: "China Eastern" },
  { code: "CZ", name: "China Southern" },
  { code: "HU", name: "Hainan Airlines" },
  { code: "JL", name: "Japan Airlines" },
  { code: "NH", name: "ANA — All Nippon Airways" },
  { code: "KE", name: "Korean Air" },
  { code: "OZ", name: "Asiana Airlines" },
  { code: "BA", name: "British Airways" },
  { code: "VS", name: "Virgin Atlantic" },
  { code: "U2", name: "easyJet" },
  { code: "FR", name: "Ryanair" },
  { code: "LH", name: "Lufthansa" },
  { code: "LX", name: "SWISS" },
  { code: "OS", name: "Austrian Airlines" },
  { code: "AF", name: "Air France" },
  { code: "KL", name: "KLM Royal Dutch Airlines" },
  { code: "IB", name: "Iberia" },
  { code: "AZ", name: "ITA Airways" },
  { code: "AY", name: "Finnair" },
  { code: "SK", name: "SAS Scandinavian Airlines" },
  { code: "TP", name: "TAP Air Portugal" },
  { code: "SN", name: "Brussels Airlines" },
  { code: "LO", name: "LOT Polish Airlines" },
  { code: "OK", name: "Czech Airlines" },
  { code: "RO", name: "TAROM" },
  { code: "JU", name: "Air Serbia" },
  { code: "A3", name: "Aegean Airlines" },
  { code: "TU", name: "Tunisair" },
  { code: "AT", name: "Royal Air Maroc" },
  { code: "AH", name: "Air Algérie" },
  { code: "ET", name: "Ethiopian Airlines" },
  { code: "KQ", name: "Kenya Airways" },
  { code: "SA", name: "South African Airways" },
  { code: "AC", name: "Air Canada" },
  { code: "AA", name: "American Airlines" },
  { code: "DL", name: "Delta Air Lines" },
  { code: "UA", name: "United Airlines" },
  { code: "WN", name: "Southwest Airlines" },
  { code: "B6", name: "JetBlue Airways" },
  { code: "AS", name: "Alaska Airlines" },
  { code: "F9", name: "Frontier Airlines" },
  { code: "NK", name: "Spirit Airlines" },
  { code: "HA", name: "Hawaiian Airlines" },
  { code: "AM", name: "Aeroméxico" },
  { code: "Y4", name: "Volaris" },
  { code: "LA", name: "LATAM Airlines" },
  { code: "AR", name: "Aerolíneas Argentinas" },
  { code: "AV", name: "Avianca" },
  { code: "CM", name: "Copa Airlines" },
  { code: "QF", name: "Qantas" },
  { code: "JQ", name: "Jetstar" },
  { code: "VA", name: "Virgin Australia" },
  { code: "NZ", name: "Air New Zealand" },
  { code: "FZ", name: "flydubai" },
  { code: "G9", name: "Air Arabia" },
  { code: "WZ", name: "Salam Air" },
  { code: "J9", name: "Jazeera Airways" },
  { code: "IY", name: "Yemenia" },
  { code: "RQ", name: "Kam Air" },
  { code: "FB", name: "Bulgaria Air" },
  { code: "EI", name: "Aer Lingus" },
  { code: "SU", name: "Aeroflot" },
  { code: "S7", name: "S7 Airlines" },
  { code: "OV", name: "SalamAir" },
  { code: "PC", name: "Pegasus Airlines" },
];

export function searchAirlines(q: string, limit = 8): Airline[] {
  const s = q.trim().toUpperCase();
  if (!s) return [];
  // Code prefix match first, then name substring
  const byCode = AIRLINES.filter((a) => a.code.startsWith(s));
  const byName = AIRLINES.filter(
    (a) => !a.code.startsWith(s) && a.name.toUpperCase().includes(s),
  );
  return [...byCode, ...byName].slice(0, limit);
}
